apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - recipesavants-efk-ingress.centralus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: recipesavants-efk-ingress.centralus.cloudapp.azure.com
  - http:
      paths:
      - path: /
        backend:
          serviceName: aks-helloworld-1-{{.Release.Name}}
          servicePort: 80

